on: push # Déclenche l'action lors d'un push
jobs: #Actions a réaliser
  build-and-push:
    name: build and push image # Nom de l'action
    runs-on: ubuntu-latest # Distribution linux utilisée
    steps:
      - name: Checkout 
        uses: actions/checkout@v2 # Fait l'action checkout, récupère le code
      - name: Run the choise script
        run: ./choise.sh # Execute le script choise.sh, qui décide quelles questions je dois répondre
      - name: Login to Docker Hub
        uses: docker/login-action@v1 # Se connecte à Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 # Prépare l'environnement pour le build
      - name: Build and push
        uses: docker/build-push-action@v2 # Build et push l'image
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/td-devops-dockerhub:tagname